<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

        <PublishDir>./publish</PublishDir>
        <PublishTrimmed>false</PublishTrimmed>
        <PublishSingleFile>false</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.19" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AdminPanel\AdminPanel.csproj" />
      <ProjectReference Include="..\APIModes\APIModes.csproj" />
      <ProjectReference Include="..\DatabaseCore\DatabaseCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="publish\web.config" />
      <_ContentIncludedByDefault Remove="publish\admin.json" />
      <_ContentIncludedByDefault Remove="publish\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="publish\appsettings.json" />
      <_ContentIncludedByDefault Remove="publish\BlazorDebugProxy\BrowserDebugHost.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="publish\publish\admin.json" />
      <_ContentIncludedByDefault Remove="publish\WebAPI.deps.json" />
      <_ContentIncludedByDefault Remove="publish\WebAPI.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="publish\WebAPI.staticwebassets.endpoints.json" />
      <_ContentIncludedByDefault Remove="publish\wwwroot\sample-data\weather.json" />
      <_ContentIncludedByDefault Remove="publish\wwwroot\_framework\blazor.boot.json" />
    </ItemGroup>

</Project>
